const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#a855f7",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f9f9f9",
    cardForeground: "#0a0a0a",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#f0f0f0",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
    userBubble: "#7c3aed",
    userBubbleText: "#ffffff",
    aiBubble: "#f0f0f0",
    aiBubbleText: "#0a0a0a",
  },
  dark: {
    text: "#fafafa",
    tint: "#c084fc",
    background: "#09090b",
    foreground: "#fafafa",
    card: "#18181b",
    cardForeground: "#fafafa",
    primary: "#a855f7",
    primaryForeground: "#ffffff",
    secondary: "#27272a",
    secondaryForeground: "#fafafa",
    muted: "#27272a",
    mutedForeground: "#a1a1aa",
    accent: "#27272a",
    accentForeground: "#fafafa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#27272a",
    input: "#27272a",
    userBubble: "#7c3aed",
    userBubbleText: "#ffffff",
    aiBubble: "#1e1e24",
    aiBubbleText: "#fafafa",
  },
  radius: 12,
};

export default colors;
